source:
  third_party_source:
    filepath_regex: [".*/cmd/.*",
                     ".*/pkg/.*",
                     ".*/hack/.*",
                     ".*/deploy/.*",
                     ".*/examples/.*",
                     ".*/vendor/.*"]
